let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB_RGB)
basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 100)
    if (maqueen.Ultrasonic(PingUnit.Centimeters) < 20) {
        maqueen.motorStop(maqueen.Motors.All)
        basic.pause(1000)
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 185)
        basic.pause(2000)
    }
})
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
})
